site_name: RPI2JAMMA Documentation

pages:
  - Home: 'index.md'

theme: readthedocs

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - toc:
      permalink: "#"
      toc_depth: "2"
